### ISSUE TITLE
Hikayeler

### ISSUE THREAD

**Issue by spasolog** [divisia/imajiner#8]
Yazdığımız hikayeleri listeleme kısmının duruşunu sevmedim.Daha farklı listeleme teknikleri kullanabilirsin.Nokta ile madde belirtilirken nokta beni tedirgin ediyor bunun yerine ok koyabilirsin veya insanlar kendi yazdıklarını kategorilendirebilmeleri için.Romantik,kurgu, fantezi kısımları olabilir yazarlar iceriklerini bu bölüme ekleyerek tertemiz ve düzenli bir hikayelerim kısmı oluşturabilir diye düşünüyorum.

Bir hikayeyi yayınlandıktan sonra çabucak ikinci hikayeme başlamak istiyor olabilirim.Bu yüzden yayınlanma yerine yeni bir hikaye yaz,yazmaya devam et ekleyebilirsin bu sayede  geri gidip tekrar yazma kısmına gitmekle canım sıkılmaz.

Yazarlar yazdıkları ve yayınladıkları hikayeleri eğer editleyebilirse bence şöyle bir kısım eklemelisin.İnsanlaelr sevdiği hikayeleri favorilerine eklesin hikaye güncellenirse güncellenen kısmın bildirisi hikayeyi favorileyenlere gelsin.Eger okurlar yeni güncellemeyi sevmezse önceki sevdikleri halı kalsin.Yani Güncelleme kısmının favorili okuyucuların okuması için kayıt ettiklerini kendileri bir butona basarak güncellendi.

Hayalet yazarın üzerine basınca hiçbir şey çıkmadı bunun yerine o bir hayalet yazısını söylemiştin bunu eklemelisin.

İnsanlar yazılarını yazarken taslak olarak kaydedilip kaydedilmedigini anlayamazlar bu yüzden beyan et yerine taslak olarak kaydet butonu olsun sonra beyan et gözüksün ya da girişte uyarı versin yazdığınız her anda cümleleriniz taslakta oluyor gibisinden.

Başlık konusunda şöyle bir fikir geldi aklima.Diyelim ilk hikayesi başlıksız ve kullanıcı adı mor başlık şöyle olabilir:Mor'un başlıksız 1. Bildirgesi ,sonra yazar ikinci kez başlıksız yazdi,Mor'un başlıksız 2. Bildirgesi gibi belli bir sayıdan sonra da baslikta su olabilir.Mor ne zaman başlık yazmayı düşünüyorsun? Muzdariplik olur hem.

**Comment by divisia** [comment]
güncellemelerden sonra sevdiği hali saklama kısmı iyiymiş olur

**Comment by divisia** [comment]
yazı yazma ekranı istesiğim gibi değil henüz kilit noktalardan biri olduğu için bayağı bir üzerine uğraşacağım

**Comment by divisia** [comment]
profil sayfası da aynı şekilde to do listemde, diğer dediklerini de düşüneceğim
