### ISSUE TITLE
Menü

### ISSUE THREAD

**Issue by spasolog** [divisia/imajiner#9]
Menününü açıp aşağı doğru indirdiğim anda bir anlam hatası görüyorum,duzeltmen dileğiyle.(bkz.imajiner bir bölge şeklinde yazan kısım)

**Comment by divisia** [comment]
nasıl bir anlam hatası

**Comment by spasolog** [comment]
Orada foto eklesem ileride hangisine ait olduğu belli olmazdi[Image]

Belki bilerek yapmissindir bilemiyom

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________
